development:
  adapter: sqlite3
  database: eastern_sierra_list_development_sqlite

test:
  adapter: sqlite3
  database: eastern_sierra_list_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: eastern_sierra_list_production
  username: eastern_sierra_list
  password: <%= ENV['EASTERN_SIERRA_LIST_DATABASE_PASSWORD'] %>
